name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9]
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Node.js dependencies
      run: |
        npm ci

    - name: Run Python linting
      run: |
        pip install flake8
        flake8 .

    - name: Run JavaScript linting
      run: |
        npm run lint

    - name: Run Python unit tests
      run: |
        pip install pytest pytest-cov
        pytest --cov=./ --cov-report=xml

    - name: Run JavaScript unit tests
      run: |
        npm test -- --coverage

    - name: Run integration tests
      run: |
        # HUMAN ASSISTANCE NEEDED
        # Add commands to run integration tests here
        # This may involve setting up a test database, running a test server, etc.

    - name: Upload Python test coverage
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        flags: python

    - name: Upload JavaScript test coverage
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage/lcov.info
        flags: javascript